# Generated by Django 6.0 on 2026-01-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0002_chat_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
