# Generated by Django 6.0 on 2026-01-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0003_message_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="token",
        ),
    ]
